"""
bssclient is a fully typed, async client for the TMDS API.
The client is _not_ autogenerated.
Find the TMDS Open API description here: https://techmasterdata.xtk-dev.de/index.html
"""

# convenience exports
from .client.bssclient import BssClient as BssClient
from .client.config import BssConfig as BssConfig
